### PR TITLE
DDFP-19 Upgraded jacoco, checkstyle, dependency-check

### LINKED ISSUE #19: Upgrade Plugins (Jacoco, Checkstyle, Dependency-check)
Upgraded Dependency-check from 5.2.2 to 5.3.1
Upgraded Checkstyle from 3.0.0 to 3.1.1
Upgraded Jacoco from 0.8.2 to 0.8.5

### PR DESCRIPTION
**Pull request by shaundmorris**
Upgraded Dependency-check from 5.2.2 to 5.3.1
Upgraded Checkstyle from 3.0.0 to 3.1.1
Upgraded Jacoco from 0.8.2 to 0.8.5

Removed customized project report output directory 

Fixes: #19 

Reviewers 
@codice/build 
@codice/continuous-integration 
@codice/test 
@codice/security 
@TonyMorrison 
@LinkMJB 
@AdamBurstynski

### CODE REVIEW

**Review by jlcsmith — APPROVED** [review]

**Review by mcalcote — APPROVED** [review]
👍

**Review by AdamBurstynski — APPROVED** [review]

**Comment by paouelle** [comment]
❗️ Make sure that the Lenient limit class will still work with this new version of jacoco

**Comment by shaundmorris** [comment]
Thanks for the reminder @paouelle. I did have to make some changes to the Lenient class and need a new release codice-maven as well. The DDF PR will have the latest ddf-parent and codice-maven so we can ensure it all works together.

**Comment by shaundmorris** [comment]
I did run the SNAPSHOT versions locally and it passed, but we know how that goes...

**Review by paouelle — APPROVED** [review]

**Pull request merged**
